name: Build Android App

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew assembleDebug --stacktrace > build.log 2>&1 || (
            echo "Build failed."
            LOG_URL=$(curl -s -F 'file=@build.log' https://0x0.st)
            echo "Log uploaded to: $LOG_URL"
            echo "$LOG_URL" > LATEST_LOG.txt
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add LATEST_LOG.txt
            git commit -m "Add latest failed log URL [skip ci]"
            git push origin HEAD:master
            exit 1
          )

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
